### ISSUE TITLE
[feature] change fit-constraints for all peaks

### ISSUE THREAD

**Issue by ToraUma1** [kurisutsukato/peak-o-mat#6]
it would be helpful if constraints could be simultaneously changed for all peaks/contributions. 

e.g. for emission spectroscopy negative amplitudes would not make sense. A simple common change to "bound 0-9999" would be nice.
or to change pos / FWHM to fixed / free, ect..

maybe some way to be able to copy-paste (constraints and boundaries) would be an easy (?) implementation

**Comment by kurisutsukato** [comment]
This is really easy to achieve with some scripting:

```
for s in project[2]:
    for f in s.model:
        if 'amp' in f:
            f.amp.amin = 0
            f.amp.amax = 1e8
            f.amp.constr = 2
```

This will add a constraint on the amplitudes of the model of every set in plot **p2**. Note that you might see the changes until the selection in the tree is changed. Adding `sync()` add the end of the script might help.

**Comment by ToraUma1** [comment]
Oh... I see, I should have closed this.

Thanks for the help!
