### ISSUE TITLE
[convenience] Unnecessary truncation of long set titles

### ISSUE THREAD

**Issue by ToraUma1** [kurisutsukato/peak-o-mat#7]
Hi, 
is there a way to change the length of the displayed set names? Ideally dynamically to the width of the "Project"-frame :)

I.e. I have this set 
![grafik](https://github.com/user-attachments/assets/8583b1e9-5d04-46cb-9530-c3612af8b375)
but have sufficient space on my screen (and in the "Project" frame)

Best,
tora

**Comment by kurisutsukato** [comment]
Fixed by commit 77a24cf
